#===============================================================================
#2020-05-08 by yangyuntian
#===============================================================================
##JDK安装###
---
- hosts: "{{host}}"
  gather_facts: true
  vars_files:
    - playbook.conf

  tasks:
    - name: "java rpm +x"
      file:
        path: "{{dest_packages_path}}/jdk/{{JDK_package}}"
        mode: "0755"

    - name: "安装 java"
      shell: "yes|rpm -ivh {{JDK_package}} --force"
      args:
        chdir: "{{dest_packages_path}}/jdk/"
      register: rpm_result
      ignore_errors: false
      when: ansible_distribution_major_version == "7"

    - name: "rpm 安装 java"
      yum:
        name: "{{dest_packages_path}}/jdk/{{JDK_package}}"
        disablerepo: "*"
#        state: present
        state: latest
      register: rpm_result
      ignore_errors: false
      when: ansible_distribution_major_version == "6"

    - name: "制作 java 的快捷方式(静态链接），以代替 gcj"
      file:
        src: "/usr/java/jdk{{JDK_version}}/bin/java"
        dest: /usr/bin/java
        mode: '0755'
        state: link
        force: yes
      when: rpm_result is changed

    - name: "制作 javac 的快捷方式(静态链接），以代替 gcj"
      file:
        src: "/usr/java/jdk{{JDK_version}}/bin/javac"
        dest: /usr/bin/javac
        mode: '0755'
        state: link
        force: yes
      when: rpm_result is changed

    - name: "配置环境变量 /etc/profile.d/java.sh"
      lineinfile:
        dest: /etc/profile.d/java.sh
        create: yes
        line: "{{item.line}}"
      with_items:
        - {line: "export JAVA_HOME=/usr/java/jdk{{JDK_version}}"}
        - {line: "export JAVA_BIN=/usr/java/jdk{{JDK_version}}/bin"}
        - {line: "export PATH=$PATH:${JAVA_HOME}/bin"}
        - {line: "export CLASSPATH=.:${JAVA_HOME}/lib/dt.jar:${JAVA_HOME}/lib/tools.jar"}
      when: rpm_result is changed

    - name: "配置环境变量 /etc/profile"
      lineinfile:
        dest: /etc/profile
        line: "{{item.line}}"
      with_items:
        - {line: "export JAVA_HOME=/usr/java/jdk{{JDK_version}}"}
        - {line: "export JAVA_BIN=/usr/java/jdk{{JDK_version}}/bin"}
        - {line: "export PATH=$PATH:${JAVA_HOME}/bin"}
        - {line: "export CLASSPATH=.:${JAVA_HOME}/lib/dt.jar:${JAVA_HOME}/lib/tools.jar"}
      when: rpm_result is changed

    - name: "加载环境变量"
      shell: source /etc/profile

    - name: "检查Java版本"
      shell: echo  "#------JDK安装情况------#" >> "{{dest_logs_path}}/VerificationResult-{{ansible_default_ipv4['address']}}-{{DATE}}.log" &&
             /usr/bin/java -version &>> "{{dest_logs_path}}/VerificationResult-{{ansible_default_ipv4['address']}}-{{DATE}}.log"