#!/bin/bash
#===============================================================================
#2020-03-02 by yangyuntian 
#===============================================================================
#### GCC安装与升级####
#===============================================================================
##centos7系统版本安装###

function GCCInstall_centos7
{
	cd ${installPath}/gcc/centos7/
	yes|unzip gcc-4.8.5-39.el7.x86_64.zip >> ${installlogsPath}/GccRunning-${Date}.log 2>&1
	cd gcc-4.8.5-39.el7.x86_64 >> ${installlogsPath}/GccRunning-${Date}.log 2>&1
	rpm -ivh cpp-4.8.5-36.el7.x86_64.rpm --nodeps --force >> ${installlogsPath}/GccRunning-${Date}.log 2>&1
	rpm -ivh gcc-4.8.5-39.el7.x86_64.rpm --nodeps --force >> ${installlogsPath}/GccRunning-${Date}.log 2>&1
	rpm -ivh glibc-devel-2.17-260.el7.x86_64.rpm --nodeps --force >> ${installlogsPath}/GccRunning-${Date}.log 2>&1
	rpm -ivh glibc-headers-2.17-260.el7.x86_64.rpm --nodeps --force >> ${installlogsPath}/GccRunning-${Date}.log 2>&1
	rpm -ivh kernel-headers-3.10.0-957.el7.x86_64.rpm --nodeps --force >> ${installlogsPath}/GccRunning-${Date}.log 2>&1
	rpm -ivh libmpc-1.0.1-3.el7.x86_64.rpm --nodeps --force >> ${installlogsPath}/GccRunning-${Date}.log 2>&1
	rpm -ivh mpfr-3.1.1-4.el7.x86_64.rpm --nodeps --force >> ${installlogsPath}/GccRunning-${Date}.log 2>&1

	echo  "#------gcc安装情况------#" >> ${installlogsPath}/VerificationResult-${Date}.log
	gcc -dumpversion &>> ${installlogsPath}/VerificationResult-${Date}.log
	echo -e "\n" >> ${installlogsPath}/VerificationResult-${Date}.log
	LOADING "gcc安装中......" 0.01
	sleep 2
	Msgbox "gcc安装完成"
	rm -rf ./gcc-4.8.5-39.el7.x86_64/ >> ${installlogsPath}/GccRunning-${Date}.log 2>&1
}

#===============================================================================
##centos6系统版本安装###

function GCCInstall_centos6
{	
	cd ${installPath}/gcc/centos6/
	yes|unzip gcc-4.4.7-18.el6.x86_64.zip >> ${installlogsPath}/GccRunning-${Date}.log 2>&1
	cd gcc-4.4.7-18.el6.x86_64/ >> ${installlogsPath}/GccRunning-${Date}.log 2>&1
	rpm -ivh ppl-0.10.2-11.el6.x86_64.rpm --nodeps --force >> ${installlogsPath}/GccRunning-${Date}.log 2>&1
	rpm -ivh cloog-ppl-0.15.7-1.2.el6.x86_64.rpm --nodeps --force >> ${installlogsPath}/GccRunning-${Date}.log 2>&1
	rpm -ivh mpfr-2.4.1-6.el6.x86_64.rpm --nodeps --force >> ${installlogsPath}/GccRunning-${Date}.log 2>&1
	rpm -ivh cpp-4.4.7-18.el6.x86_64.rpm --nodeps --force >> ${installlogsPath}/GccRunning-${Date}.log 2>&1
	rpm -ivh kernel-headers-2.6.32-696.el6.x86_64.rpm --nodeps --force >> ${installlogsPath}/GccRunning-${Date}.log 2>&1
	rpm -ivh glibc-headers-2.12-1.209.el6.x86_64.rpm --nodeps --force >> ${installlogsPath}/GccRunning-${Date}.log 2>&1
	rpm -ivh glibc-devel-2.12-1.209.el6.x86_64.rpm --nodeps --force >> ${installlogsPath}/GccRunning-${Date}.log 2>&1
	rpm -ivh gcc-4.4.7-18.el6.x86_64.rpm --nodeps --force >> ${installlogsPath}/GccRunning-${Date}.log 2>&1
	rpm -ivh libstdc++-devel-4.4.7-18.el6.x86_64.rpm --nodeps --force >> ${installlogsPath}/GccRunning-${Date}.log 2>&1
	rpm -ivh gcc-c++-4.4.7-18.el6.x86_64.rpm --nodeps --force >> ${installlogsPath}/GccRunning-${Date}.log 2>&1
	
	echo  "#------gcc安装情况------#" >> ${installlogsPath}/VerificationResult-${Date}.log
	gcc -dumpversion &>> ${installlogsPath}/VerificationResult-${Date}.log
	echo -e "\n" >> ${installlogsPath}/VerificationResult-${Date}.log
	LOADING "gcc安装中......" 0.01
	sleep 2
	Msgbox "gcc安装完成"
	rm -rf ./gcc-4.4.7-18.el6.x86_64/ >> ${installlogsPath}/GccRunning-${Date}.log 2>&1
}